// Ol3-Cesium. See https://github.com/openlayers/ol3-cesium/
// License: https://github.com/openlayers/ol3-cesium/blob/master/LICENSE
// Version: v1.6-17-ga496037

(function(){var l,m=this;function n(a){return void 0!==a}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==p(a)}function aa(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function s(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function t(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return u.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function v(a,b){var c=a.split("."),d=m;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}function w(a,b){function c(){}c.prototype=b.prototype;a.ra=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ta=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function x(a,b){this.map=a;this.e=null;this.scene=b;this.b=null;this.h=[];this.o={};this.d={};this.f=this.g=null;this.map.on("change:view",function(){this.D(this.map.getView())},this);this.D(this.map.getView());this.map.on("change:layergroup",function(){ha(this,this.map.getLayers())},this);ha(this,this.map.getLayers())}x.prototype.D=function(a){this.e=a;ia(this);this.q()};
function ha(a,b){null===a.b||y(a.h,a.b.unByKey);a.b=b;if(null===b)a.h=[];else{var c=u(function(){this.q()},a);a.h=[b.on("add",c),b.on("remove",c)]}ia(a);a.q()}x.prototype.q=function(){null!==this.e&&null!==this.b&&(this.g=ja(this.d),this.f=ka(this.o),this.k(!1),this.b.forEach(function(a){la(this,a)},this),y(ma(this.f),function(a){var b=this.o[a];n(b)&&(delete this.o[a],null===b||this.T(b))},this),this.f=null,na(this.g,function(a,b){y(a,this.map.unByKey);delete this.d[b]},this),this.g=null)};
function la(a,b){if(null!==b){var c=t(b);if(b instanceof ol.layer.Group){var d=b.getLayers();n(d)&&d.forEach(function(a){la(this,a)},a);if(!n(a.d[c])){var e=[];a.d[c]=e;var f,g=[],h=u(function(){f=b.getLayers();if(n(f)){var a=u(function(){this.q()},this);g=[f.on("add",a),f.on("remove",a)];e.push.apply(e,g)}},a);h();e.push(b.on("change:layers",function(){y(g,function(a){oa(e,a);f.unByKey(a)});h()}))}delete a.g[c]}else b instanceof ol.layer.Layer&&(d=a.o[c],n(d)||(d=a.S(b),a.o[c]=d),null!=d&&(a.l(d),
delete a.f[d]))}}function ia(a){a.k(!0);a.o={}};function z(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(z,Error);z.prototype.name="CustomError";function pa(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}function qa(a){if(!ra.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(va,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(wa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(xa,"&#0;"));return a}
var sa=/&/g,ta=/</g,ua=/>/g,va=/"/g,wa=/'/g,xa=/\x00/g,ra=/[\x00&<>"']/;function ya(a,b){return a<b?-1:a>b?1:0};function za(a,b){b.unshift(a);z.call(this,pa.apply(null,b));b.shift()}w(za,z);za.prototype.name="AssertionError";function A(a,b){throw new za("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var B=Array.prototype;function y(a,b,c){B.forEach.call(a,b,c)}function oa(a,b){var c=B.indexOf.call(a,b,void 0),d;(d=0<=c)&&B.splice.call(a,c,1);return d}function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var C;a:{var Ba=m.navigator;if(Ba){var Ca=Ba.userAgent;if(Ca){C=Ca;break a}}C=""}function E(a){return-1!=C.indexOf(a)};function Da(){return m.navigator||null}var Ea=E("Opera")||E("OPR"),F=E("Trident")||E("MSIE"),H=E("Gecko")&&-1==C.toLowerCase().indexOf("webkit")&&!(E("Trident")||E("MSIE")),I=-1!=C.toLowerCase().indexOf("webkit");I&&E("Mobile");var J,Fa=Da();J=Fa&&Fa.platform||"";J.indexOf("Mac");J.indexOf("Win");J.indexOf("Linux");Da()&&(Da().appVersion||"").indexOf("X11");var K=C;K&&K.indexOf("Android");K&&K.indexOf("iPhone");K&&K.indexOf("iPad");function Ga(){var a=m.document;return a?a.documentMode:void 0}
var Ha=function(){var a="",b;if(Ea&&m.opera)return a=m.opera.version,"function"==p(a)?a():a;H?b=/rv\:([^\);]+)(\)|;)/:F?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:I&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(C))?a[1]:"");return F&&(b=Ga(),b>parseFloat(a))?String(b):a}(),Ia={};
function L(a){var b;if(!(b=Ia[a])){b=0;for(var c=String(Ha).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var G=k.exec(g)||["","",""],D=r.exec(h)||["","",""];if(0==G[0].length&&0==D[0].length)break;b=ya(0==G[1].length?0:parseInt(G[1],10),0==D[1].length?0:parseInt(D[1],10))||ya(0==G[2].length,0==D[2].length)||
ya(G[2],D[2])}while(0==b)}b=Ia[a]=0<=b}return b}var Ja=m.document,Ka=Ja&&F?Ga()||("CSS1Compat"==Ja.compatMode?parseInt(Ha,10):5):void 0;var La=!F||F&&9<=Ka,Ma=F&&!L("9");!I||L("528");H&&L("1.9b")||F&&L("8")||Ea&&L("9.5")||I&&L("528");H&&!L("8")||F&&L("9");function Na(){0!=Oa&&t(this)}var Oa=0;function M(a,b){this.type=a;this.a=this.target=b}M.prototype.b=function(){};function Pa(a){Pa[" "](a);return a}Pa[" "]=function(){};function N(a,b){M.call(this,a?a.type:"");this.d=this.state=this.a=this.target=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&H)try{Pa(c.nodeName)}catch(d){}this.state=a.state;this.d=a;a.defaultPrevented&&this.b()}}w(N,M);N.prototype.b=function(){N.ra.b.call(this);var a=this.d;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ma)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var O="closure_listenable_"+(1E6*Math.random()|0),Qa=0;function Ra(a,b,c,d,e){this.p=a;this.proxy=null;this.src=b;this.type=c;this.G=!!d;this.H=e;++Qa;this.A=this.F=!1}function Sa(a){a.A=!0;a.p=null;a.proxy=null;a.src=null;a.H=null};function na(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function ma(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function ja(a){var b={},c;for(c in a)b[c]=a[c];return b}function ka(a){var b={},c;for(c in a)b[a[c]]=c;return b}var Ta="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Ua(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ta.length;f++)c=Ta[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function P(a){this.src=a;this.a={};this.b=0}P.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Va(a,b,d,e);-1<g?(b=a[g],c||(b.F=!1)):(b=new Ra(b,this.src,f,!!d,e),b.F=c,a.push(b));return b};P.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Va(e,b,c,d);return-1<b?(Sa(e[b]),B.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function Wa(a,b){var c=b.type;c in a.a&&oa(a.a[c],b)&&(Sa(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Va(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.A&&f.p==b&&f.G==!!c&&f.H==d)return e}return-1};var Xa="closure_lm_"+(1E6*Math.random()|0),Ya={},Za=0;function $a(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)$a(a,b[f],c,d,e);return null}c=ab(c);return a&&a[O]?a.h(b,c,d,e):bb(a,b,c,!1,d,e)}function bb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=cb(a);h||(a[Xa]=h=new P(a));c=h.add(b,c,d,e,f);if(c.proxy)return c;d=db();c.proxy=d;d.src=a;d.p=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(gb(b.toString()),d);Za++;return c}
function db(){var a=hb,b=La?function(c){return a.call(b.src,b.p,c)}:function(c){c=a.call(b.src,b.p,c);if(!c)return c};return b}function ib(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)ib(a,b[f],c,d,e);else c=ab(c),a&&a[O]?a.u.add(String(b),c,!0,d,e):bb(a,b,c,!0,d,e)}function jb(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)jb(a,b[f],c,d,e);else(c=ab(c),a&&a[O])?a.u.remove(String(b),c,d,e):a&&(a=cb(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Va(b,c,!!d,e)),(c=-1<a?b[a]:null)&&kb(c))}
function kb(a){if("number"!=typeof a&&a&&!a.A){var b=a.src;if(b&&b[O])Wa(b.u,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.G):b.detachEvent&&b.detachEvent(gb(c),d);Za--;(c=cb(b))?(Wa(c,a),0==c.b&&(c.src=null,b[Xa]=null)):Sa(a)}}}function gb(a){return a in Ya?Ya[a]:Ya[a]="on"+a}function lb(a,b,c,d){var e=1;if(a=cb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.G==c&&!f.A&&(e&=!1!==mb(f,d))}return Boolean(e)}
function mb(a,b){var c=a.p,d=a.H||a.src;a.F&&kb(a);return c.call(d,b)}
function hb(a,b){if(a.A)return!0;if(!La){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new N(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;0<=h;h--)c.a=e[h],d&=lb(e[h],f,!0,c);for(h=0;h<e.length;h++)c.a=e[h],d&=lb(e[h],f,!1,c)}return d}return mb(a,
new N(b,this))}function cb(a){a=a[Xa];return a instanceof P?a:null}var nb="__closure_events_fn_"+(1E9*Math.random()>>>0);function ab(a){return"function"==p(a)?a:a[nb]||(a[nb]=function(b){return a.handleEvent(b)})};function ob(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};function Q(a,b,c){Na.call(this);this.h=a;this.g=c;this.b=b||window;this.d=u(this.f,this)}w(Q,Na);Q.prototype.a=null;Q.prototype.e=!1;Q.prototype.start=function(){pb(this);this.e=!1;var a=qb(this),b=rb(this);a&&!b&&this.b.mozRequestAnimationFrame?(this.a=$a(this.b,"MozBeforePaint",this.d),this.b.mozRequestAnimationFrame(null),this.e=!0):this.a=a&&b?a.call(this.b,this.d):this.b.setTimeout(ob(this.d),20)};
function pb(a){if(null!=a.a){var b=qb(a),c=rb(a);b&&!c&&a.b.mozRequestAnimationFrame?kb(a.a):b&&c?c.call(a.b,a.a):a.b.clearTimeout(a.a)}a.a=null}Q.prototype.f=function(){this.e&&this.a&&kb(this.a);this.a=null;this.h.call(this.g,ga())};function qb(a){a=a.b;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null}
function rb(a){a=a.b;return a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null};function R(a,b){this.a=a;this.b=null;this.k=n(b)?b:null;this.f=!1;this.h=new Cesium.Event;this.d=document.createElement(sb);this.d.width=1;this.d.height=1;this.a.on("change",function(){tb(this)},this);tb(this)}w(R,Cesium.ImageryProvider);
Object.defineProperties(R.prototype,{ready:{get:function(){return this.f}},rectangle:{get:function(){return this.l}},tileWidth:{get:function(){var a=this.a.getTileGrid();return null===a?256:a.getTileSize(0)}},tileHeight:{get:function(){return this.tileWidth}},maximumLevel:{get:function(){var a=this.a.getTileGrid();return null===a?18:a.getMaxZoom()}},minimumLevel:{get:function(){return 0}},tilingScheme:{get:function(){return this.e}},tileDiscardPolicy:{get:function(){}},errorEvent:{get:function(){return this.h}},
credit:{get:function(){return this.g}},proxy:{get:function(){}},hasAlphaChannel:{get:function(){return!0}},ua:{get:function(){}}});function tb(a){if(!a.f&&"ready"==a.a.getState()){var b=a.a.getProjection();a.b=null!=b?b:a.k;if(a.b==ol.proj.get("EPSG:4326"))a.e=new Cesium.GeographicTilingScheme;else if(a.b==ol.proj.get("EPSG:3857"))a.e=new Cesium.WebMercatorTilingScheme;else return;a.l=a.e.rectangle;b=ub(a.a);a.g=null===b?void 0:b;a.f=!0}}
function ub(a){var b="",c=a.getAttributions();null===c||y(c,function(a){b+=a.getHTML().replace(/<\/?[^>]+(>|$)/g,"")+" "});var d,e;0==b.length&&(a=a.getLogo(),n(a)&&(s(a)?d=a:(d=a.src,e=a.href)));return n(d)||0<b.length?new Cesium.Credit(b,d,e):null}R.prototype.getTileCredits=function(){};R.prototype.getTileCredits=R.prototype.getTileCredits;
R.prototype.requestImage=function(a,b,c){var d=this.a.getTileUrlFunction();if(null===d||null===this.b)return this.d;a=d([this.e instanceof Cesium.GeographicTilingScheme?c+1:c,a,-b-1],1,this.b);return n(a)?Cesium.ImageryProvider.loadImage(this,a):this.d};R.prototype.requestImage=R.prototype.requestImage;function vb(a,b,c,d,e){var f=Cesium.Math.clamp,g=Cesium.defaultValue;e=e||{};var h=g(e.duration,500),k=g(e.easing,ol.easing.linear),r=e.callback,G=ga(),D=0,eb=new Cesium.Matrix4,fb=new Q(function(e){e=k(f((e-G)/h,0,1));a.transform.clone(eb);var g=(e-D)*b;D=e;a.lookAtTransform(d);a.rotate(c,g);a.lookAtTransform(eb);1>e?fb.start():r&&r()});fb.start()}function wb(a,b){var c=a.camera.getPickRay(b);return a.globe.pick(c,a)||a.camera.pickEllipsoid(b)}
function xb(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height/2);return wb(a,b)}function yb(a,b,c){var d=new Cesium.Cartesian3,e=new Cesium.Cartesian3,f=new Cesium.Cartesian3;Cesium.Cartesian3.normalize(a,d);Cesium.Cartesian3.normalize(b,e);Cesium.Cartesian3.cross(d,e,f);a=Cesium.Cartesian3.dot(d,e);b=Cesium.Cartesian3.magnitude(f);c=Cesium.Cartesian3.dot(c,f);f=Math.atan2(b,a);return 0<=c?f:-f}
function zb(a,b){var c=a.camera,d=c.frustum.fovy/2,e;e=a.camera;var f=e.direction,g=Cesium.Quaternion.fromAxisAngle(e.right,e.frustum.fovy/2),g=Cesium.Matrix3.fromQuaternion(g),h=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(g,f,h);e=new Cesium.Ray(e.position,h);e=Cesium.Cartesian3.clone(e.direction);Cesium.Cartesian3.negate(e,e);f=new Cesium.Cartesian3;Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(b,f);g=new Cesium.Cartesian3;Cesium.Cartesian3.negate(c.right,g);return yb(f,e,g)+d}
function Ab(a,b,c){n(c)&&(c=c.getHeight(b),b.height=n(c)?c:0);c=Cesium.Ellipsoid.WGS84;b=c.cartographicToCartesian(b);var d=a.position,e=new Cesium.Cartesian3;c.geocentricSurfaceNormal(d,e);a.lookAt(d,b,e)}function Bb(a,b){if(null===a||null===b)return null;var c=ol.proj.transformExtent(a,b,"EPSG:4326");return Cesium.Rectangle.fromDegrees(c[0],c[1],c[2],c[3])}
function Cb(a,b){if(!(a instanceof ol.layer.Tile))return null;var c=null,c=a.getSource();if(!(c instanceof ol.source.WMTS)&&c instanceof ol.source.TileImage){var d=c.getProjection();if(null===d)d=b;else if(d!==b)return null;var e=d===ol.proj.get("EPSG:3857"),d=d===ol.proj.get("EPSG:4326");if(e||d)c=new R(c,b);else return null}else return null;e={};d=a.getExtent();null!=d&&null!==b&&(e.rectangle=Bb(d,b));return new Cesium.ImageryLayer(c,e)}
function Db(a,b){var c=a.getOpacity();n(c)&&(b.alpha=c);c=a.getVisible();n(c)&&(b.show=c);c=a.getSaturation();n(c)&&(b.saturation=c);c=a.getContrast();n(c)&&(b.contrast=c);c=a.getBrightness();n(c)&&(b.brightness=Math.pow(1+parseFloat(c),2))}function S(a){return 2<a.length?Cesium.Cartesian3.fromDegrees(a[0],a[1],a[2]):Cesium.Cartesian3.fromDegrees(a[0],a[1])}function Eb(a){for(var b=[],c=0;c<a.length;++c)b.push(S(a[c]));return b}
function T(a,b){var c=ol.proj.get("EPSG:4326"),d=ol.proj.get(b);if(d!==c){var e=a.getProperties();a=a.clone();a.transform(d,c);a.setProperties(e)}return a}function Fb(a){a=a||"black";if(q(a))return new Cesium.Color(Cesium.Color.byteToFloat(a[0]),Cesium.Color.byteToFloat(a[1]),Cesium.Color.byteToFloat(a[2]),a[3]);if(s(a))return Cesium.Color.fromCssColorString(a);A("impossible")};function U(a,b){this.c=a;this.b=a.camera;this.i=b;this.k=this.a=null;this.f=this.d=Gb;this.e=this.g=0;this.h=null;this.l=!1;this.i.on("change:view",function(){this.D(this.i.getView())},this);this.D(this.i.getView())}function Gb(a,b,c){c=c||a.length;if(b)for(var d=0;d<c;++d)b[d]=a[d];return a}l=U.prototype;
l.D=function(a){null!==this.a&&(this.a.unByKey(this.k),this.k=null);this.a=a;if(null===a)this.f=this.d=Gb;else{var b=ol.proj.getTransform(a.getProjection(),"EPSG:4326"),c=ol.proj.getTransform("EPSG:4326",a.getProjection());this.d=b;this.f=c;this.k=a.on("propertychange",this.fa,this);this.v()}};l.fa=function(){this.l||this.v()};l.pa=function(a){null===this.a||this.a.setRotation(a)};l.ha=function(){if(null!==this.a){var a=this.a.getRotation();return n(a)?a:0}};l.qa=function(a){this.g=a;Hb(this)};
l.ea=function(){return this.g};l.na=function(a){this.e=a;Hb(this);this.r()};l.ba=function(){return this.e};l.ka=function(a){null===this.a||this.a.setCenter(a)};l.getCenter=function(){return null===this.a?void 0:this.a.getCenter()};l.la=function(a){null!==this.d&&(a=this.d(a),a=new Cesium.Cartographic(a[0]*Math.PI/180,a[1]*Math.PI/180,this.Z()),this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(a),this.r())};
l.ia=function(){if(null!==this.f){var a=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);return this.f([180*a.longitude/Math.PI,180*a.latitude/Math.PI])}};l.ma=function(a){var b=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);b.height=a;this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b);this.r()};l.Z=function(){return Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position).height};
l.ja=function(a){null!==this.d&&(a=this.d(a),a=Cesium.Cartographic.fromDegrees(a[0],a[1]),Ab(this.b,a,this.c.globe),this.r())};function Hb(a){if(null!==a.a&&null!==a.d){var b=a.a.getCenter();if(b){b=a.d(b);b=new Cesium.Cartographic(b[0]*Math.PI/180,b[1]*Math.PI/180);if(a.c.globe){var c=a.c.globe.getHeight(b);b.height=n(c)?c:0}a.b.setView({positionCartographic:b,pitch:a.g-Cesium.Math.PI_OVER_TWO,heading:-a.a.getRotation()});a.b.moveBackward(a.e);Ib(a,!0)}}}
l.v=function(){if(null!==this.a&&null!==this.d){var a=this.a.getCenter();if(null!=a){var b=this.d(a),a=this.a.getResolution(),a=n(a)?a:0,b=b[1]*Math.PI/180,c=this.c.canvas,d=this.b.frustum.fovy,e=this.a.getProjection().getMetersPerUnit();this.e=a*c.height*e*Math.cos(Math.abs(b))/2/Math.tan(d/2);Hb(this)}}};
l.r=function(){if(null!==this.a&&null!==this.f){this.l=!0;var a=Cesium.Ellipsoid.WGS84,b=this.c,c=xb(b),d=c;d||(d=b.globe,b=this.b.positionCartographic.clone(),d=d.getHeight(b),b.height=n(d)?d:0,d=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b));this.e=Cesium.Cartesian3.distance(d,this.b.position);b=a.cartesianToCartographic(d);this.a.setCenter(this.f([180*b.longitude/Math.PI,180*b.latitude/Math.PI]));this.a.setResolution(Jb(this,this.e,b?b.latitude:0));if(c){d=this.b.position;b=new Cesium.Cartesian3;
a.geocentricSurfaceNormal(c,b);a=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(d,c,a);Cesium.Cartesian3.normalize(a,a);var d=this.b.up,e=this.b.right,f=new Cesium.Cartesian3(-c.y,c.x,0),e=Cesium.Cartesian3.angleBetween(e,f),c=Cesium.Cartesian3.cross(c,d,new Cesium.Cartesian3).z;this.a.setRotation(0>c?e:-e);c=Math.acos(Cesium.Cartesian3.dot(b,a));this.g=isNaN(c)?0:c}else this.a.setRotation(this.b.heading),this.g=-this.b.pitch+Math.PI/2;this.l=!1}};
function Ib(a,b){var c=a.b.viewMatrix;a.h&&a.h.equals(c)||(a.h=c.clone(),!0!==b&&a.r())}function Jb(a,b,c){var d=a.c.canvas,e=a.b.frustum.fovy;a=a.a.getProjection().getMetersPerUnit();return 2*b*Math.tan(e/2)/a/Math.cos(Math.abs(c))/d.height};function Kb(a,b){Cesium.PrimitiveCollection.call(this);var c=new Cesium.BillboardCollection({scene:b}),d=new Cesium.PrimitiveCollection;this.a={projection:a,billboards:c,featureToCesiumMap:{},primitives:d};this.add(c)}w(Kb,Cesium.PrimitiveCollection);function V(){Na.call(this);this.u=new P(this);this.k=this}w(V,Na);V.prototype[O]=!0;V.prototype.removeEventListener=function(a,b,c,d){jb(this,a,b,c,d)};function Lb(a,b){var c=a.k,d=b,e=d.type||d;if(s(d))d=new M(d,c);else if(d instanceof M)d.target=d.target||c;else{var f=d,d=new M(e,c);Ua(d,f)}c=d.a=c;Mb(c,e,!0,d);Mb(c,e,!1,d)}V.prototype.h=function(a,b,c,d){return this.u.add(String(a),b,!1,c,d)};
function Mb(a,b,c,d){if(b=a.u.a[String(b)]){b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.A&&g.G==c){var h=g.p,k=g.H||g.src;g.F&&Wa(a.u,g);e=!1!==h.call(k,d)&&e}}}};function W(a){a=n(a)?a:{};V.call(this);this.b=this.c=null;this.a=new Cesium.RectanglePrimitive({asynchronous:!1,rectangle:new Cesium.Rectangle,material:Cesium.Material.fromType(Cesium.Material.ColorType)});this.a.material.uniforms.color=new Cesium.Color(0,0,1,.5);this.d=n(a.ga)?a.ga:Cesium.KeyboardEventModifier.SHIFT;this.e=null}w(W,V);
W.prototype.l=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.position);a=this.c.globe.pick(a,this.c);n(a)&&(this.b.setInputAction(u(this.f,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE),this.b.setInputAction(u(this.g,this),Cesium.ScreenSpaceEventType.LEFT_UP),n(this.d)&&(this.b.setInputAction(u(this.f,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.d),this.b.setInputAction(u(this.g,this),Cesium.ScreenSpaceEventType.LEFT_UP,this.d)),b=b.cartesianToCartographic(a),a=this.a.rectangle,
a.north=a.south=b.latitude,a.east=a.west=b.longitude,this.a.height=b.height,this.a.show=!0,Lb(this,{type:"boxstart",position:b}),this.c.primitives.contains(this.a)||this.c.primitives.add(this.a),this.c.screenSpaceCameraController.enableInputs=!1,this.e=b)};
W.prototype.f=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.endPosition);a=this.c.globe.pick(a,this.c);n(a)&&(b=b.cartesianToCartographic(a),this.a.height=Math.max(this.a.height,b.height),b.latitude<this.e.latitude?this.a.rectangle.south=b.latitude:this.a.rectangle.north=b.latitude,b.longitude<this.e.longitude?this.a.rectangle.west=b.longitude:this.a.rectangle.east=b.longitude)};
W.prototype.g=function(a){var b=this.c.globe.ellipsoid;a=this.c.camera.getPickRay(a.position);a=this.c.globe.pick(a,this.c);n(a)&&(b=b.cartesianToCartographic(a),this.a.show=!1,Lb(this,{type:"boxend",position:b}),this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE),n(this.d)&&(this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP,this.d),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.d)));this.c.screenSpaceCameraController.enableInputs=
!0};W.prototype.I=function(a){null===a?(this.c.primitives.contains(this.a)&&this.c.primitives.remove(this.a),null!==this.b&&(this.b.destroy(),this.b=null)):(this.b=new Cesium.ScreenSpaceEventHandler(a.canvas),this.b.setInputAction(u(this.l,this),Cesium.ScreenSpaceEventType.LEFT_DOWN,this.d));this.c=a};function X(a){this.scene=a}function Nb(a,b,c,d,e){var f={flat:!0,renderState:{depthTest:{enabled:!0}}};n(e)&&(f.renderState||(f.renderState={}),f.renderState.lineWidth=e);e=new Cesium.PerInstanceColorAppearance(f);c=new Cesium.GeometryInstance({geometry:c,attributes:{color:Cesium.ColorGeometryInstanceAttribute.fromColor(d)}});c=new Cesium.Primitive({geometryInstances:c,appearance:e});c.olLayer=a;c.olFeature=b;return c}
function Ob(a,b){var c=a.getFill()?a.getFill().getColor():null,d=a.getStroke()?a.getStroke().getColor():null,e="black";d&&b?e=d:c&&(e=c);return Fb(e)}function Pb(a,b){var c=b.getStroke()?b.getStroke().getWidth():1;return Math.min(c,a.scene.maximumAliasedLineWidth)}function Qb(a,b,c,d,e,f){var g=Ob(f,!1),h=Ob(f,!0),k=new Cesium.PrimitiveCollection;f.getFill()&&(d=Nb(b,c,d,g),k.add(d));f.getStroke()&&(a=Pb(a,f),d=Nb(b,c,e,h,a),k.add(d));return k}
function Rb(a,b,c,d,e,f){var g;f instanceof Cesium.PrimitiveCollection?g=f:(g=new Cesium.PrimitiveCollection,g.add(f));if(!e.getText())return g;e=e.getText();(a=a.V(b,c,d,e))&&g.add(a);return g}l=X.prototype;l.R=function(a,b,c,d){a=a.add(b);a.olLayer=c;a.olFeature=d;return a};
l.U=function(a,b,c,d,e){c=T(c,d);d=c.getCenter();var f=3==d.length?d[2]:0,g=d.slice();g[0]+=c.getRadius();d=S(d);var g=S(g),h=Cesium.Cartesian3.distance(d,g),g=new Cesium.CircleGeometry({center:d,radius:h,height:f});d=new Cesium.CircleOutlineGeometry({center:d,radius:h,extrudedHeight:f,height:f});d=Qb(this,a,b,g,d,e);return Rb(this,a,b,c,e,d)};
l.N=function(a,b,c,d,e){c=T(c,d);var f=Eb(c.getCoordinates());d=new Cesium.PolylineMaterialAppearance({material:this.X(0,e,!0)});f=new Cesium.PolylineGeometry({positions:f,width:Pb(this,e),vertexFormat:d.vertexFormat});d=new Cesium.Primitive({geometryInstances:new Cesium.GeometryInstance({geometry:f}),appearance:d});d.olLayer=a;d.olFeature=b;return Rb(this,a,b,c,e,d)};
l.O=function(a,b,c,d,e){c=T(c,d);for(var f=c.getLinearRings(),g=d={},h=0;h<f.length;++h){var k=f[h].getCoordinates(),k=Eb(k);0==h?d.positions=k:(d.holes={positions:k},d=d.holes)}f=new Cesium.PolygonGeometry({polygonHierarchy:g,perPositionHeight:!0});d=new Cesium.PolygonOutlineGeometry({polygonHierarchy:d,perPositionHeight:!0});d=Qb(this,a,b,f,d,e);return Rb(this,a,b,c,e,d)};
l.M=function(a,b,c){c=c.get("altitudeMode");n(c)||(c=b.get("altitudeMode"));n(c)||(c=a.get("altitudeMode"));a=Cesium.HeightReference.NONE;"clampToGround"===c?a=Cesium.HeightReference.CLAMP_TO_GROUND:"relativeToGround"===c&&(a=Cesium.HeightReference.RELATIVE_TO_GROUND);return a};
l.K=function(a,b,c,d,e,f,g){c=T(c,d);var h=e.getImage(),k=h.getImage(1),r=u(function(){if(null!==k&&(k instanceof HTMLCanvasElement||k instanceof Image||k instanceof HTMLImageElement)){var d=c.getCoordinates(),d=S(d),e,r=h.getOpacity();n(r)&&(e=new Cesium.Color(1,1,1,r));r=this.M(a,b,c);e=this.R(f,{image:k,color:e,heightReference:r,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,position:d},a,b);g&&g(e)}},this);k instanceof Image&&(""==k.src||0==k.naturalHeight||0==k.naturalWidth||!k.complete)?ib(k,"load",
function(){r()}):r();return e.getText()?Rb(this,a,b,c,e,new Cesium.Primitive):null};
l.W=function(a,b,c,d,e,f,g){function h(c,f){var g=new Cesium.PrimitiveCollection;y(c,function(c){g.add(f(a,b,c,d,e))});return g}switch(c.getType()){case "MultiPoint":c=c.getPoints();if(e.getText()){var k=new Cesium.PrimitiveCollection;y(c,function(c){(c=this.K(a,b,c,d,e,f,g))&&k.add(c)}.bind(this));return k}y(c,function(c){this.K(a,b,c,d,e,f,g)});return null;case "MultiLineString":return c=c.getLineStrings(),h(c,this.N.bind(this));case "MultiPolygon":return c=c.getPolygons(),h(c,this.O.bind(this));
default:A("Unhandled multi geometry type"+c.getType())}};
l.V=function(a,b,c,d){var e=d.getText(),f=new Cesium.LabelCollection({scene:this.scene}),g=ol.extent.getCenter(c.getExtent());if(c instanceof ol.geom.SimpleGeometry){var h=c.getFirstCoordinate();g[2]=3==h.length?h[2]:0}h={};h.position=S(g);h.text=e;h.heightReference=this.M(a,b,c);c=d.getOffsetX();e=d.getOffsetY();0!=c&&0!=e&&(c=new Cesium.Cartesian2(c,e),h.pixelOffset=c);c=d.getFont();null!=c&&(h.font=c);c=void 0;d.getFill()&&(h.fillColor=Ob(d,!1),c=Cesium.LabelStyle.FILL);d.getStroke()&&(h.outlineWidth=
Pb(this,d),h.outlineColor=Ob(d,!0),c=Cesium.LabelStyle.OUTLINE);d.getFill()&&d.getStroke()&&(c=Cesium.LabelStyle.FILL_AND_OUTLINE);h.style=c;if(d.getTextAlign()){var k;switch(d.getTextAlign()){case "center":k=Cesium.HorizontalOrigin.CENTER;break;case "left":k=Cesium.HorizontalOrigin.LEFT;break;case "right":k=Cesium.HorizontalOrigin.RIGHT;break;default:A("unhandled text align "+d.getTextAlign())}h.horizontalOrigin=k}if(d.getTextBaseline()){var r;switch(d.getTextBaseline()){case "top":r=Cesium.VerticalOrigin.TOP;
break;case "middle":r=Cesium.VerticalOrigin.CENTER;break;case "bottom":r=Cesium.VerticalOrigin.BOTTOM;break;case "alphabetic":r=Cesium.VerticalOrigin.TOP;break;case "hanging":r=Cesium.VerticalOrigin.BOTTOM;break;default:A("unhandled baseline "+d.getTextBaseline())}h.verticalOrigin=r}d=f.add(h);d.olLayer=a;d.olFeature=b;return f};
l.X=function(a,b,c){a=b.getFill();b=b.getStroke();if(c&&!b||!c&&!a)return null;a=c?b.getColor():a.getColor();a=Fb(a);return c&&b.getLineDash()?Cesium.Material.fromType("Stripe",{horizontal:!1,repeat:500,evenColor:a,oddColor:new Cesium.Color(0,0,0,0)}):Cesium.Material.fromType("Color",{color:a})};l.L=function(a,b,c,d){a=b.getStyleFunction();var e;n(a)&&(e=a.call(b,d));null==e&&null!=c&&(e=c(b,d));return n(e)?e[0]:null};
l.J=function(a,b,c,d,e){function f(a){d.featureToCesiumMap[t(b)]=a}e=e||b.getGeometry();var g=d.projection;if(!e)return null;switch(e.getType()){case "GeometryCollection":var h=new Cesium.PrimitiveCollection;y(e.getGeometries(),function(e){e&&(e=this.J(a,b,c,d,e))&&h.add(e)}.bind(this));return h;case "Point":return(e=this.K(a,b,e,g,c,d.billboards,f))?e:null;case "Circle":return this.U(a,b,e,g,c);case "LineString":return this.N(a,b,e,g,c);case "Polygon":return this.O(a,b,e,g,c);case "MultiPoint":case "MultiLineString":case "MultiPolygon":return(e=
this.W(a,b,e,g,c,d.billboards,f))?e:null;case "LinearRing":throw Error("LinearRing should only be part of polygon.");default:throw Error("Ol geom type not handled : "+e.getType());}};l.Y=function(a,b,c){var d=a.getSource().getFeatures(),e=b.getProjection();b=b.getResolution();if(!n(b)||!e)throw A("View not ready"),Error("View not ready");for(var e=new Kb(e,this.scene),f=e.a,g=0;g<d.length;++g){var h=d[g];if(null!=h){var k=a.getStyleFunction();if(k=this.L(0,h,k,b))if(k=this.J(a,h,k,f))c[t(h)]=k,e.add(k)}}return e};
l.Q=function(a,b,c,d){var e=b.getProjection();b=b.getResolution();if(!n(b)||!e)return null;var f=a.getStyleFunction();b=this.L(0,c,f,b);if(!b)return null;d.projection=e;return this.J(a,c,b,d)};var Sb=!F||F&&9<=Ka;!H&&!F||F&&F&&9<=Ka||H&&L("1.9.1");F&&L("9");var sb="CANVAS";function Tb(a){var b=document;return s(a)?b.getElementById(a):a}
function Ub(a){var b=a||document,c=null;if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".ol-overlaycontainer");else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".ol-overlaycontainer");else if(a.getElementsByClassName){var e=a.getElementsByClassName("ol-overlaycontainer");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className,g;if(g="function"==typeof f.split)g=0<=B.indexOf.call(f.split(/\s+/),"ol-overlaycontainer",void 0);
g&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null}function Vb(a,b){na(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Wb?a.setAttribute(Wb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Wb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Xb(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!Sb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',qa(g.name),'"');if(g.type){f.push(' type="',qa(g.type),'"');var h={};Ua(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(s(g)?f.className=g:q(g)?f.className=g.join(" "):Vb(f,g));2<d.length&&Yb(e,f,d);return f}
function Yb(a,b,c){function d(c){c&&b.appendChild(s(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!aa(f)||ba(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ba(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==p(f)){g="function"==typeof f.item;break a}}g=!1}y(g?Aa(f):f,d)}}}function Zb(a){if(void 0!=a.nextElementSibling)a=a.nextElementSibling;else for(a=a.nextSibling;a&&1!=a.nodeType;)a=a.nextSibling;return a};function Y(a,b){this.t=b.imageryLayers;this.C=new Cesium.ImageryLayerCollection;x.call(this,a,b)}w(Y,x);Y.prototype.l=function(a){this.t.add(a);this.C.add(a)};Y.prototype.T=function(a){a.destroy()};Y.prototype.k=function(a){for(var b=0;b<this.C.length;++b)this.t.remove(this.C.get(b),a);this.C.removeAll(!1)};
Y.prototype.S=function(a){if(!(a instanceof ol.layer.Tile))return null;var b=this.e.getProjection(),c=Cb(a,b);null!==c&&(a.on("change:brightness change:contrast change:hue change:opacity change:saturation change:visible".split(" "),function(){null===c||Db(a,c)}),Db(a,c),a.on("change:extent",function(){this.t.remove(c,!0);this.C.remove(c,!1);delete this.o[t(a)];this.q()},this),a.on("change",function(){var a=this.t.indexOf(c);0<=a&&(this.t.remove(c,!1),this.t.add(c,a))},this));return c};function Z(a,b,c){this.I=c||new X(b);this.a=new Cesium.PrimitiveCollection;b.primitives.add(this.a);this.a.destroyPrimitives=!1;x.call(this,a,b)}w(Z,x);Z.prototype.l=function(a){this.a.add(a)};Z.prototype.T=function(a){a.destroy()};Z.prototype.k=function(a){this.a.destroyPrimitives=a;this.a.removeAll();this.a.destroyPrimitives=!1};
Z.prototype.S=function(a){if(!(a instanceof ol.layer.Vector))return null;var b=this.e,c=a.getSource(),d={},e=this.I.Y(a,b,d);a.on("change:visible",function(){e.show=a.getVisible()});var f=u(function(c){var f=this.I.Q(a,b,c,e.a);f&&(d[t(c)]=f,e.add(f))},this),g=u(function(a){var b=a.getGeometry();a=t(a);if(null!=b&&"Point"==b.getType()){var b=e.a,c=b.billboards,f=b.featureToCesiumMap[a];delete b.featureToCesiumMap[a];null!=f&&c.remove(f)}b=d[a];delete d[a];null!=b&&e.remove(b)},this);c.on("addfeature",
function(a){f(a.feature)},this);c.on("removefeature",function(a){g(a.feature)},this);c.on("changefeature",function(a){a=a.feature;g(a);f(a)},this);return e};function $(a){this.i=a.map;this.b=Xb("DIV",{style:"position:absolute;top:0;left:0;width:100%;height:100%;visibility:hidden;"});var b=Tb(a.target||null);if(b)b.appendChild(this.b);else{var c=this.i.getViewport();(c=Ub(c))&&c.parentNode&&c.parentNode.insertBefore(this.b,c)}this.d=null==b;this.j=Xb(sb,{style:"position:absolute;top:0;left:0;width:100%;height:100%;"});this.j.oncontextmenu=function(){return!1};this.j.onselectstart=function(){return!1};this.b.appendChild(this.j);this.n=!1;this.P=[];this.a=
null;this.c=new Cesium.Scene({canvas:this.j,scene3DOnly:!0});b=this.c.screenSpaceCameraController;b.inertiaSpin=0;b.ineartiaTranslate=0;b.inertiaZoom=0;b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.SHIFT});b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.ALT});b.enableLook=!1;this.c.camera.constrainedAxis=Cesium.Cartesian3.UNIT_Z;this.s=new U(this.c,this.i);this.e=new Cesium.Globe(Cesium.Ellipsoid.WGS84);
this.c.globe=this.e;this.c.skyAtmosphere=new Cesium.SkyAtmosphere;a=n(a.createSynchronizers)?a.createSynchronizers(this.i,this.c):[new Y(this.i,this.c),new Z(this.i,this.c)];for(b=a.length-1;0<=b;--b)a[b].q();this.d&&(a=Zb(this.j),null!=a&&(a.style.display="none"));this.s.v();this.B=new Q(function(){this.c.initializeFrame();var a=this.j.clientWidth,b=this.j.clientHeight;if(this.j.width!==a||this.j.height!==b)this.j.width=a,this.j.height=b,this.c.camera.frustum.aspectRatio=a/b;this.c.render();this.n&&
Ib(this.s);this.B.start()},void 0,this)}l=$.prototype;l.$=function(){return this.s};l.da=function(){return this.i};l.aa=function(){return this.c};l.ca=function(){return this.n};
l.oa=function(a){if(this.n!=a)if(this.n=a,this.b.style.visibility=this.n?"visible":"hidden",this.n){if(this.d){var b=this.i.getInteractions();b.forEach(function(a){this.P.push(a)},this);b.clear();a=this.i.getLayerGroup();a.getVisible()&&(this.a=a,this.a.setVisible(!1))}this.s.v();this.B.start()}else this.d&&(b=this.i.getInteractions(),y(this.P,function(a){b.push(a)},this),this.P.length=0,null!==this.a&&(this.a.setVisible(!0),this.a=null)),this.s.r(),pb(this.B)};
l.sa=function(a,b){if(!this.n){this.s.v();var c=this.e.ellipsoid,d=this.c.camera,e=c.cartesianToCartographic(d.position);e.height<a&&(e.height=a,d.position=c.cartographicToCartesian(e));this.B.start();var f=this;setTimeout(function(){!f.n&&pb(f.B)},b)}};v("olcs.AbstractSynchronizer",x);x.prototype.synchronize=x.prototype.q;v("olcs.Camera",U);U.prototype.setHeading=U.prototype.pa;U.prototype.getHeading=U.prototype.ha;U.prototype.setTilt=U.prototype.qa;U.prototype.getTilt=U.prototype.ea;U.prototype.setDistance=U.prototype.na;U.prototype.getDistance=U.prototype.ba;U.prototype.setCenter=U.prototype.ka;U.prototype.getCenter=U.prototype.getCenter;U.prototype.setPosition=U.prototype.la;U.prototype.getPosition=U.prototype.ia;U.prototype.setAltitude=U.prototype.ma;
U.prototype.getAltitude=U.prototype.Z;U.prototype.lookAt=U.prototype.ja;U.prototype.readFromView=U.prototype.v;U.prototype.updateView=U.prototype.r;v("olcs.core.computePixelSizeAtCoordinate",function(a,b){var c=a.camera,d=a.canvas,e=c.frustum,d=new Cesium.Cartesian2(d.width,d.height),c=Cesium.Cartesian3.magnitude(Cesium.Cartesian3.subtract(c.position,b,new Cesium.Cartesian3));return e.getPixelSize(d,c)});
v("olcs.core.applyHeightOffsetToGeometry",function(a,b){a.applyTransform(function(a,d,e){if(n(e)&&3<=e)for(a=0;a<d.length;a+=e)d[a+2]+=b;return d})});v("olcs.core.rotateAroundAxis",vb);
v("olcs.core.setHeadingUsingBottomCenter",function(a,b,c){var d=a.camera;a=zb(a,c);a=Cesium.Quaternion.fromAxisAngle(d.right,a);var e=Cesium.Matrix3.fromQuaternion(a),f=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(d.position,c,f);a=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(e,f,a);Cesium.Cartesian3.add(a,c,a);c=Cesium.Matrix4.fromTranslation(a);vb(d,b,a,c)});v("olcs.core.pickOnTerrainOrEllipsoid",wb);
v("olcs.core.pickBottomPoint",function(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height);return wb(a,b)});v("olcs.core.pickCenterPoint",xb);
v("olcs.core.computeSignedTiltAngleOnGlobe",function(a){var b=a.camera,c=new Cesium.Ray(b.position,b.direction);a=a.globe.pick(c,a);if(!a){var d=Cesium.IntersectionTests.rayEllipsoid(c,Cesium.Ellipsoid.WGS84);d&&(a=Cesium.Ray.getPoint(c,d.start))}if(a)return c=new Cesium.Cartesian3,Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(a,c),b=yb(b.direction,c,b.right)-Math.PI,Cesium.Math.convertLongitudeRange(b)});v("olcs.core.computeAngleToZenith",zb);v("olcs.core.lookAt",Ab);
v("olcs.core.extentToRectangle",Bb);v("olcs.core.tileLayerToImageryLayer",Cb);v("olcs.core.updateCesiumLayerProperties",Db);v("olcs.core.ol4326CoordinateToCesiumCartesian",S);v("olcs.core.ol4326CoordinateArrayToCsCartesians",Eb);v("olcs.core.olGeometryCloneTo4326",T);v("olcs.core.convertColorToCesium",Fb);v("olcs.DragBox",W);W.prototype.setScene=W.prototype.I;W.prototype.listen=W.prototype.h;v("olcs.FeatureConverter",X);X.prototype.csAddBillboard=X.prototype.R;
X.prototype.olCircleGeometryToCesium=X.prototype.U;X.prototype.olLineStringGeometryToCesium=X.prototype.N;X.prototype.olPolygonGeometryToCesium=X.prototype.O;X.prototype.getHeightReference=X.prototype.M;X.prototype.olPointGeometryToCesium=X.prototype.K;X.prototype.olMultiGeometryToCesium=X.prototype.W;X.prototype.olGeometry4326TextPartToCesium=X.prototype.V;X.prototype.olStyleToCesium=X.prototype.X;X.prototype.computePlainStyle=X.prototype.L;X.prototype.olFeatureToCesium=X.prototype.J;
X.prototype.olVectorLayerToCesium=X.prototype.Y;X.prototype.convert=X.prototype.Q;v("olcs.OLCesium",$);$.prototype.getCamera=$.prototype.$;$.prototype.getOlMap=$.prototype.da;$.prototype.getCesiumScene=$.prototype.aa;$.prototype.getEnabled=$.prototype.ca;$.prototype.setEnabled=$.prototype.oa;$.prototype.warmUp=$.prototype.sa;v("olcs.RasterSynchronizer",Y);v("olcs.VectorSynchronizer",Z);})();
