#!/bin/bash
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

if [ -f rc_$TARGET ]; then
    source rc_$TARGET
    if [[ $CODE_DIR == */branch/* ]]; then
        make preparebranch
        if [ -f rc_branch ]; then
            source rc_branch
        fi
    fi
    make all
fi

exit $?
