#!/bin/bash
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

if [[ $CODE_DIR != */branch/* ]]; then
    echo "doing standard post-restore-code work..."
    if [ -f rc_$TARGET ]; then
        source rc_$TARGET
        make cleanrc all
    fi
else
    echo "doing branch post-restore-code work..."
    echo $TARGET
    echo $PROJECT_NAME
    echo $CODE_DIR
    make preparebranch SERVICE_URL=//mf-chsdi3.$TARGET.bgdi.ch
    if [ -f rc_branch ]; then
        source rc_branch
        make cleanrc all
    fi
fi

exit $?
