#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#
if [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 restart
fi

exit 0
