#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#
if [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 restart
fi

# We should check if apache is running and return error if it's not
sleep 5
sudo /etc/init.d/apache2 status

apache_rc=$?

if [ $apache_rc -ne 0 ]; then

  echo "-----------Deploy Error----------"
  echo "Apache is not running on the deployed instance. Aborting deployment. Please check  instance"
  echo "-----------End of Deploy Error----------"

else

  # We wait to assure that varnishes had time to detect running apache again
  # before we deploy to next instance
  echo "Waiting 70 seconds before continuing. Give varnish time to rediscover this instance..."
  sleep 70

fi

exit $apache_rc
